DATASET_PATH = 'dataset.csv'
DATASET_SEP = ';'
DATASET_ENCODING = 'iso-8859-1'

OUTPUT_PATH = 'output'

SLICE_KEY = 'SLICE'
SLICE_PREV_VAL = 'preventivato'
SLICE_ACTUAL_VAL = 'actual'

YEAR_WEEK_DEPARTMENT_KEY = 'Year_Week_Reparto'
ACTIVITY_KEY = 'ID_PAZ_DATA'
TIMESTAMP_KEY = 'DATA'
URGENCY_TYPE_KEY = 'TIPO_URGENZA'
RESERVE_KEY = 'RISERVA'